name = "my-first-worker"
type = "webpack"
account_id = "14b5ecd8916149ea7cea5208c57b3944"
workers_dev = false
zone_id = "bd5e3317c90835eed8110082ffb4315b"
routes = [
  "https://www.verema.com/blog/*",
  "https://www.verema.com/bodegas/*",
  "https://www.verema.com/foros/*",
  "https://www.verema.com/restaurantes/*",
  "https://www.verema.com/vinos/*"
]
